name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install GNOME SDK
        run: |
          flatpak install --system --noninteractive flathub org.gnome.Platform//49 org.gnome.Sdk//49

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --disable-rofiles-fuse --repo=repo build-dir com.fless.Client.yaml

      - name: Create .flatpak bundle
        run: |
          flatpak build-bundle repo fless-client-x86_64.flatpak com.fless.Client master

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} fless-client-x86_64.flatpak --repo ${{ github.repository }}
